// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: proto/message.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageExampleClient is the client API for MessageExample service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageExampleClient interface {
	ServerReply(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type messageExampleClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageExampleClient(cc grpc.ClientConnInterface) MessageExampleClient {
	return &messageExampleClient{cc}
}

func (c *messageExampleClient) ServerReply(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/MessageExample/ServerReply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageExampleServer is the server API for MessageExample service.
// All implementations must embed UnimplementedMessageExampleServer
// for forward compatibility
type MessageExampleServer interface {
	ServerReply(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedMessageExampleServer()
}

// UnimplementedMessageExampleServer must be embedded to have forward compatible implementations.
type UnimplementedMessageExampleServer struct {
}

func (UnimplementedMessageExampleServer) ServerReply(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerReply not implemented")
}
func (UnimplementedMessageExampleServer) mustEmbedUnimplementedMessageExampleServer() {}

// UnsafeMessageExampleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageExampleServer will
// result in compilation errors.
type UnsafeMessageExampleServer interface {
	mustEmbedUnimplementedMessageExampleServer()
}

func RegisterMessageExampleServer(s grpc.ServiceRegistrar, srv MessageExampleServer) {
	s.RegisterService(&MessageExample_ServiceDesc, srv)
}

func _MessageExample_ServerReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageExampleServer).ServerReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessageExample/ServerReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageExampleServer).ServerReply(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageExample_ServiceDesc is the grpc.ServiceDesc for MessageExample service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageExample_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MessageExample",
	HandlerType: (*MessageExampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServerReply",
			Handler:    _MessageExample_ServerReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/message.proto",
}
